export const handleError = (async ({ error, event }) => {
    console.log(String(e));

    return {
        message: 'Whoops!',
    };
}) satisfies HandleServerError;